name: opentada_flutter
description: An Interactive Fiction engine.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0 # For making HTTP requests to Gemini API
  flutter_secure_storage: ^9.0.0 # For storing API key securely
  # shared_preferences: ^2.2.2 # Alternative for local storage if secure_storage is not desired for some reason

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - books/The Beloved Dead Chapter 0.tada