name: tada
description: An Interactive Fiction engine.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Ensure compatibility with latest Flutter features

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0 # Use a recent version for Gemini API
  file_picker: ^6.1.1 # For file selection
  shared_preferences: ^2.2.2 # For local key-value storage
  path_provider: ^2.1.1 # For accessing standard paths
  # cupertino_icons: ^1.0.2 # Included by default, but good to be aware of

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true